[project]
name = "coin"
version = "0.0.1"
description = "A package to simulate coins"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["coin"]